### ISSUE TITLE
Repeatedly using ctrl + t locks up keyboard input for AWT renderer

### ISSUE THREAD

**Issue by dmarcuse** [CCEmuX/CCEmuX#108]
This one can be a bit inconsistent, but if you're using the AWT renderer, repeatedly terminating can lock up keyboard input. Simply running and terminating the `lua` program can cause it.

**Comment by LDDestroier** [comment]
I can attest to this. Sometimes key events will stop locking up, but it's unreliable doing so. "mouse_click", "mouse_scroll", and "mouse_drag" events all still work, though.

**Comment by dmarcuse** [comment]
I think it may be an issue with how we track modifier key states, I'll have to do some testing. As a temporary workaround, try using the JFX renderer, which has a different input system (you'll need JavaFX installed of course) - change the `renderer` value to `JFX` in the config.

**Comment by SquidDev** [comment]
Cross posting from the forum thread:

> I think this might be a similar (?) issue, so I figured I'd put it here.
> 
> This only seems to happen after forcefully rebooting the computer with CTRL+R. The `key_up` events at the top (which map to CTRL and R, respectively) always seem to make it through when the bug occurs, but after that, no key events make it through.
> 
> ![](https://i.imgur.com/YtCqg2x.png)

**Comment by atenfyr** [comment]
Yeah, I should have put that screenshot here rather than the forum thread. Just tested it out, and I'm also having the same problem that was originally reported, so I'm assuming it just happens with all shortcuts.

**Comment by SquidDev** [comment]
I've just pushed a commit which fixed the issues I was able to reproduce. Can you all update and double check this works for you? (you'll need to run the emulator, wait for it to download and then restart it) If not, do say and I'll reopen the issue.

**Comment by atenfyr** [comment]
Seems to work for me! 🎉
