### ISSUE TITLE
Scrolling down pings back up

### ISSUE THREAD

**Issue by deathlynocturnal** [CCEmuX/CCEmuX#111]
Hard to explain this one, but I am using a MacBook Pro. If I use the mouse pad, and scroll down, it like bounces back up, so when I scroll down a bit, it will usually try to scroll back up a bit.

It's hard to explain but it like starts scrolling down then scrolls back up, weird, anyway I have attached a video for reference: https://kaos-network.com/files/ccemux-bug.mp4 here I am just trying to scroll down.

**Comment by SquidDev** [comment]
Can you run `while true do print(os.pullEvent()) end`? Just to see what it's printing?

**Comment by blunty666** [comment]
I'm having the same issue when scrolling on my laptop mouse pad as well.

Scroll Up (works ok):
![image](https://user-images.githubusercontent.com/16059025/42137283-9b618136-7d61-11e8-8011-113b7316c387.png)

Scroll Down (it will scroll down first then scroll back up):
![image](https://user-images.githubusercontent.com/16059025/42137290-c282b8d4-7d61-11e8-822b-0757b4579106.png)

**Comment by SquidDev** [comment]
I've pushed an attempt fix for this: can you both update (you'll need to run it, wait for it to update, and run again) and see if it's fixed anything?

**Comment by blunty666** [comment]
Yep that's fixed it! Scrolling is working perfectly now.

**Comment by SquidDev** [comment]
Fantastic, thanks for testing!
