### ISSUE TITLE
Java Exception Thrown after latest update - d365524b

### ISSUE THREAD

**Issue by blunty666** [CCEmuX/CCEmuX#112]
I'm getting the error below after the auto-update to the latest version.

I can revert to the previous version by modifying the launcher.properties file, but it will then update it again at next launch!

![image](https://user-images.githubusercontent.com/16059025/42137247-ffc70160-7d60-11e8-938b-d44313e4a05d.png)

**Comment by SquidDev** [comment]
Sorry, I fixed this in 355203b083a18afd3eebb45efc27b624ee852675 but didn't update the website. Can you update and confirm it is fixed?

**Comment by dmarcuse** [comment]
Side note - to prevent the launcher automatically updating, you should set the version number (like you did) and also set `updateSite=` to prevent it downloading new versions.

**Comment by blunty666** [comment]
Fixed! I'll remember the updateSite= trick just in case something similar happens again
