### ISSUE TITLE
file.seek() exists

### ISSUE THREAD

**Issue by shelbykauth** [CCEmuX/CCEmuX#122]
So I'm doing a thing with parsing Midi Files.  Actually reading the files is an excellent use for an emulator.
I was struggling with the fact that reading the wrong number of bytes could be throw everything off, so when I found this function, I was in heaven.  Used it everywhere.
```lua
file = fs.open(path, "rb")
totalSize = file.seek("end")
file.seek("set", 0)
```
Then I loaded up Minecraft and ran the same code.  "attempt to call field 'seek' (a nil value)"
file.seek does not exist in CCTweaked, but it does appear in CCEmuX.

**Comment by shelbykauth** [comment]
*is sheepish*

So it turns out I had CCTweaked pr1.7, and it's now on CCTweaked pr1.12
file.seek() was added sometime between the two.
I'm leaving this here in case anyone else runs into the same issue.

**Comment by Lemmmy** [comment]
[1.80pr1.9](https://github.com/SquidDev-CC/CC-Tweaked/releases/tag/v1.80pr1.9)

**Comment by SquidDev** [comment]
CCEmuX should be on 1.80pr1.11, so make sure you're running the latest version.
