### ISSUE TITLE
Custom data directory?

### ISSUE THREAD

**Issue by Alee14** [CCEmuX/CCEmuX#124]
Hey uh does anyone know how to set a custom data directory, like back when I used CCEmuRedux I could set my own data directory in the same directory as the jar file and if it's already implemented in CCEmuX please tell me :)

**Comment by Lustyn** [comment]
Yes. You can supply the `-d` or `--data-dir` argument to the jar when running it.

However, it would appear that the current release of the launcher available from the [site](https://emux.cc) does not correctly pass arguments to the actual emulator.

Additionally, there are tools like [CCRunX](https://forums.computercraft.cc/index.php?topic=93.0) (unrelated to CCEmuX but a cool project nonetheless) that allow you to easily set up workspaces for your project without having to deal with a global data directory if that's your thing.

**Comment by dmarcuse** [comment]
If you're running CCEmuX directly from the command line (not via the launcher), you can use the `-d`/`--data-dir` option to specify a custom directory. The code for the launcher supports this as well as of 9b5dfba, but it hasn't yet had a release including that commit.

**Comment by Lustyn** [comment]
Ninja'd

**Comment by Alee14** [comment]
Ahh thanks :P
