### ISSUE TITLE
mouse_drag for one mouse button can be confused by another

### ISSUE THREAD

**Issue by LDDestroier** [CCEmuX/CCEmuX#125]
If you click and drag a mouse button (doesn't matter which), and then, while it's held, click, drag, and release another mouse button, any further dragging with the first mouse button will return mouse_drag events corresponding to the second mouse button.

Basically:
1. hold LMB on screen
2. move mouse
3. hold RMB on screen
4. move mouse
5. release RMB
6. move mouse  **<-- Will give you mouse_drag events with button 2 instead of 1**

I'm on the latest version as of today. (version 1.1.0, "ccemux/versions/af12e2e4/CCEmuX-cct.jar")

**Comment by dmarcuse** [comment]
What's expected (CC) behavior in this case, drag events for both buttons?

**Comment by LDDestroier** [comment]
The expected behavior is that it would give mouse_drag events for the button that's being held down. However, what's happening is that I drag one mouse button, drag/release another, and it will give me drag events for the latter instead of the former. That's the issue here.

**Comment by dmarcuse** [comment]
Ah, misread the issue.

**Comment by SquidDev** [comment]
OK, we're now consistent with CC's behaviour. I'm not going to argue that that behaviour is entirely sane, but that's not CCEmuX's decision to make.
