### ISSUE TITLE
Turtle emulator?

### ISSUE THREAD

**Issue by Lupus590** [CCEmuX/CCEmuX#126]
Possibly have a screen which lets the user build a fake world for the turtle to run in and a debug option which blocks turtle functions (allowing the user to simulate the real world as the emulator will only know what the turtle would from turtle.inspect)

I'm aware that this is a big ask and might take a while or be out of scope.

**Comment by dmarcuse** [comment]
I've considered something like this in the past, and while I'm not opposed to it, my main worry is scope and feature creep. We'd effectively be reimplementing the Minecraft world, and how much of it do we want to emulate? Blocks? Dropped items? Gravity affecting dropped items? Weather? Redstone? And so on...

**Comment by SquidDev** [comment]
I'm inclined to agree with ape here - a turtle emulator is probably out of scope of CCEmuX itself. Getting something which works well and accurately is a lot of effort - it's just going to be easier to launch Minecraft.

It would be possible to implement a plugin which does something like this, though obviously it'd be tied to a specific rendering backend. 

The alternative would be to write something entirely in Lua - it's pretty trivial to emulate the turtle API, so the hard bit would be getting some interface for placing blocks/viewing the world. You could probably get away with something quite simple, like a 2D top-down/from the side view.
