### ISSUE TITLE
Screenshotting / GIF recording

### ISSUE THREAD

**Issue by znepb** [CCEmuX/CCEmuX#128]
Just as the title says. A keybind or key (prntscreen) to save the screen to a file, or record a GIF.

**Comment by Lustyn** [comment]
There are already [some tools](http://www.computercraft.info/forums2/index.php?/topic/24840-recgif/) made within ComputerCraft to achieve such a task. I'd say while it would be a nice feature, it's probably just not going to happen any time soon as no one has the interest to implement it directly in the emulator.

**Comment by SquidDev** [comment]
Duplicate of #34. It's on my radar, I just hadn't worked out a nice way to expose it in in the API.
