### ISSUE TITLE
How do users access APIs and ROM files?

### ISSUE THREAD

**Issue by ejm554** [CCEmuX/CCEmuX#129]
Hello. I have a little experience with the CC: Tweaked mod for MInecraft, and I've started playing around with CCEmuX as a way to code without launching the game. This looks to be a cool project!

**I'd like to understand how can a user can access, edit, and create APIs and/or the ROM files in CCEmuX.** I posted a [similar question](https://github.com/SquidDev-CC/CC-Tweaked/issues/322) on the CC:T project site, and I learned that their preferred method is through Minecraft resource packs.

But since Minecraft is not used with CCEmuX, I presume the resource-pack technique isn't applicable. If I'm right, then **is there a recommended way to play with my own custom files?** I reviewed the documentation, and I couldn't find an answer.

I did try using a legacy method available to ComputerCraft users prior to version 1.55, and it looks like it might work. Namely, I opened the CCEmuX support directories (`~/Library/Application Support/ccemux/assets/computercraft/lua`), and added a ROM subdirectory with nested folders, i.e., `apis`, `help`, `programs`. I could then use CCEmuX to see and interact with example files that I placed in there. 

**Should I continue to use this so-called legacy method?**

![Screen Shot 2020-01-25 at 1 41 57 PM](https://user-images.githubusercontent.com/26723535/73126577-18a13700-3f7a-11ea-9ce5-ba41836c30b8.png)

![Screen Shot 2020-01-25 at 1 48 14 PM](https://user-images.githubusercontent.com/26723535/73126553-c3fdbc00-3f79-11ea-88c6-e5175dd2bd6b.png)

**Comment by SquidDev** [comment]
Yep! [As we mention briefly on the website](https://emux.cc/tips.html#custom-rom), what you've found is the correct way to do it.

CCEmuX uses the 1.12 version of CC and CC:T, as they are the main version of both, and so we use the 1.12 layout of resource packs.

**Comment by ejm554** [comment]
Oh, my apologies. I think I saw that section of the documentation, but I must of overlooked it. I think I was thrown by talk of creating "your own `bios.lua` file."

A couple follow-up questions:
-  Is there a way to use CCEmuX to interact with my existing CC:T files, and/or switch between the Minecraft mod and the emulator? If not, do users who want to play in both environments just manually copy their files between the two hierarchies? 
- You mentioned that CCEmuX uses 1.12, but my startup screen shows "CraftOS 1.8." Shouldn't I expect to see "CraftOS 1.12?"

![Screen Shot 2020-01-25 at 2 25 26 PM](https://user-images.githubusercontent.com/26723535/73126994-8c920e00-3f7f-11ea-9859-891d0849d092.png)

**Comment by plt-amy** [comment]
> Is there a way to use CCEmuX to interact with my existing CC:T files, and/or switch between the Minecraft mod and the emulator? If not, do users who want to play in both environments just manually copy their files between the two hierarchies?

You can make your CCEmuX computer folder and your CC:T computer folder symbolic and/or hard links. (`man 1 ln`)

**Comment by SquidDev** [comment]
> Is there a way to use CCEmuX to interact with my existing CC:T files

_Technically_ yes, but it's not especially nice. Basically, you can start the emulator with the `-d` flag, which species a data directory.

```
> java -jar ccemux-launcher.jar -d 'CC-Tweaked/run/saves/New World/'
```

Note if you're running CC:Tweaked 1.13+, you'll need to do `New World/computercraft` instead.

This really isn't a good solution though, as it basically copies your configs there. It would be nice if you could point the emulator at arbitrary directories - I'll open an issue.

> You mentioned that CCEmuX uses 1.12, but my startup screen shows "CraftOS 1.8." Shouldn't I expect to see "CraftOS 1.12?"

There's not really any link between the CraftOS version number and the Minecraft one. CC: Tweaked for 1.12-1.15 uses CraftOS 1.8 (as does CC for 1.8.9-1.12).

Historically this referred to the version of ComputerCraft you were using at the time (i.e. CC 1.5x used CraftOS 1.5), but CC:T uses a slightly different versioning scheme so it's not really true any more.

**Comment by SquidDev** [comment]
Oh, probably also worth mentioning [CCRunX](https://github.com/daelvn/ccrunx), which provides a way to start a computer in a folder. But really something we should support natively.

**Comment by SquidDev** [comment]
OK, you can now run CCEmuX with `-C CC-Tweaked/run/saves/New World/computer/` (or `-C CC-Tweaked/run/saves/New World/computercraft/computer`) and it'll use your normal settings.

**Comment by ejm554** [comment]
Thank you! That was fast! But I could use a little more hand-holding here.

- Where exactly do I put the `-C` and the path to try this out? Looking over your code, I can see references to "user config," but can't see that phrase when I open the CCEmuX Config Editor with `emu config`. 
- Does the `New World` substring indicate that I can only use this feature with _new_ worlds, or can I just replace that substring with an existing world name?
- What's the difference between `.../New World/computer/` and `.../New World/computercraft/computer`?

**Comment by SquidDev** [comment]
Yeah, sorry! My explanation was probably not very clear unless you're me.

Basically the `-C` needs to be passed [on the command line](https://emux.cc/cli.html). I'm afraid I'm not entirely well versed in Macs, but basically open a terminal in the same folder you saved the `ccemux-launcher.jar` file, and run:

```
java -jar ccemux-launcher.jar -C $PATH_TO_MINECRAFT_SAVE/computercraft/computer
```

You should replace `$PATH_TO_MINECRAFT_SAVE` with wherever your Minecraft world is. For me, that's `C:\Users\JonathanCoates\AppData\Roaming\.minecraft\saves\New World`. This can be run on any save, existing or otherwise. Yep, "New World" was just an example from my computer.

> What's the difference between `.../New World/computer/` and `.../New World/computercraft/computer`?

On older versions of Minecraft (1.12 and before), we saved computers in a `$WORLD/computer` folder. In 1.13+ we save them in `$WORLD/computercraft/computer`. Basically, you want the folder which has all the computer data in it (so has children named `0`, `1`, etc...).

I'd definitely like to make this more accessible in the future. I'm not sure I want to put it in the main config, as I do want people to be able to easily switch between directories, but hopefully we'll work something out.

Hope that helps a wee bit! Do shout if you're still confused, or have other questions/comments.

**Comment by dmarcuse** [comment]
Maybe it would be worth adding a config field to the launcher specifying default arguments if none others are passed, or arguments to be appended?

**Comment by SquidDev** [comment]
Hrmr, maybe? Personally I'd just edit my `.desktop` file (well, the Windows equivalent), but I realise that's probably more technical than we'd like.

**Comment by dmarcuse** [comment]
Maybe a profile system in the launcher could work, where profiles can override configs/arguments and be selected before starting the emulator

**Comment by SquidDev** [comment]
Yeah, I'm in mixed minds about that. In some ways, doing it in the launcher would be more flexible, as you could even have profiles which launch CC and others with CC:T (or even different emulator versions).

That said, the launcher doesn't receive updates, and personally I'd prefer to keep it as minimal as possible. It'd definitely work within the emulator - you could have a `profiles` section of `ccemux.json`, and then display a profile select screen if there's more than one profile (and no directory-override arguments have been passed).

That said, I'm not sure how the interface would work in that case. Don't really want the renderers to handle it (it's just another thing to support), but obviously do not want to be launching GUIs in TRoR mode.
