### ISSUE TITLE
Startup is blocked by FileMount scanning

### ISSUE THREAD

**Issue by SquidDev** [CCEmuX/CCEmuX#132]
When CCEmuX starts up (or creates any computer), we first construct an `EmulatedComputer` and then create a renderer using that computer. However, constructing an `EmulatedComputer` may be incredibly slow in some cases, which makes the perceived startup of the emulator much slower.

The specific case I'm having issues with is with `FileMount` scanning my entire computer directory in order to determine its size. Locally, my `computer/0` folder takes up a ~114Mb, which takes CC ~5 seconds to scan (thanks Windows). This means that the emulator can take upwards of 10 seconds to start (and `emu open 0` takes 5-6s).

Sadly, I don't think this problem is avoidable - startup is the only sane time to compute the disk's size. However, I wonder if we can change how computers are booted in order to reduce the _perceived_ startup time - if we can show a frame as soon as possible, it's obvious we're doing something, rather than just being slow.

I suspect the easiest way to do this would be to make `EmulatedComputer.Builder.setRootMount` accept a `Supplier<IWriteableMount>` instead, making it lazy. This allows us to defer construction of the mount until it's absolutely needed. I don't know if that's enough - I can't quite recall how CCEmuX boots computers right now.

**Comment by dmarcuse** [comment]
If the delay is caused by the mount scanning the directory, presumably it would affect people using the mod as well - would it be better to try to fix this in CC itself? Perhaps by lazily counting the size of the mount and deferring write operations until it's known?

**Comment by SquidDev** [comment]
> If the delay is caused by the mount scanning the directory, presumably it would affect people using the mod as well - would it be better to try to fix this in CC itself?

This _generally_ isn't a problem within CC, as you don't have 100MB folders. I agree that it'd be better to defer it within CC (or see if we can optimise it), but it's also tricky to do.

> Sadly, I don't think this problem is avoidable - startup is the only sane time to compute the disk's size. 

What I mean here is that deferring is possible, but ugly. If file scanning is going to take 6 seconds, you really need to do it asynchronously, as otherwise you run the risk of the first write operation causing "too long without yielding" errors. However, in order to make it asynchronous, it means we now need to make all `fs.` methods yield, and I don't really want to think about how many changes that'd require :).

**Comment by dmarcuse** [comment]
Looking into CC:T's code, it looks like `FileMount.measureUsedSpace` is implemented using the `java.io` filesystem API. I think it'd be worth trying to use nio instead here - IIRC, Windows provides file metadata when listing directory contents, which is discarded when using `java.io.File.list`, but if `Files.walkFileTree` were used, the metadata is available to the `FileVisitor`. If this is implemented using the metadata provided from listing the directory, it could be significantly faster right off the bat.

**Comment by SquidDev** [comment]
Ahh, that's a very good point. I'd rather forgotten that nio provided a saner file traversal system. I'll have a fiddle and see.

**Comment by SquidDev** [comment]
Just currently constructing a FileMount for my computer directory takes 1.3s. Switching to use `Files.walkFileTree` appears to reduce this to 0.66s[^1].

That's a definite improvement. Though obviously not the 5-6s of startup I'm seeing above, so I assume there's something else going on here which is responsible for the bad performance. I'm going to leave this open for the time being, until I can work it out.

[^1]: I did warm up the JIT after testing both of these, but didn't bother to dig out JMH, so this isn't a proper™ benchmark.
