### ISSUE TITLE
ComputerCraft abstraction layer

### ISSUE THREAD

**Issue by SquidDev** [CCEmuX/CCEmuX#133]
This is something I mentioned to @Lemmmy quite recently, but I think it's worth creating an issue so this can be planned a little better.

As CC:Tweaked has developed, it has continued to diverge from ComputerCraft. As a result, many of the internals are rather different, which means both CC:T and CCEmuX need to jump through several hoops to ensure compatibility.

CCEmuX currently compiles with 48 warnings, almost all of them due to using deprecated methods. As CC:T continues to change, this problem is only going to get worse, especially if we consider the upcoming changes to `Terminal`s (I think at least, I haven't seen the work).

While it might be sensible possible to drop support for vanilla CC, I'd rather not for the time being. Instead, I'd like to remove any reference to CC from the public API, implementing an abstraction layer instead.

Effectively, I'm imagining splitting CCEmuX into the following sub-projects:

 - **API:** This would expose the current CCEmuX API, a repackaged version of CC:T's API, and some internal classes (such as `Terminal` and `Computer`).

   I think repackaging (so effectively copying a subset of `dan200.computercraft.api` into `cc.emux.api.computercraft` or `net.clgd.ccemux.api.computercraft`) rather than just using CC:T's API directly is the most sane thing to do, as I can't guarantee the two will remain compatible in later versions of Minecraft.

   Also, as I can't guarantee how CC:T's API will develop in the future, I don't really want to wed ourselves to a stable API in the style of Sponge. Given how there's not many (any?) external plugins right now using the API, I don't think this is a big issue, but happy to discuss further :).

 - **Core and plugins:** This implements the core of CCEmuX (plugin loader, etc...) and any of the built-in plugins. There's an argument plugins should be shipped off into a separate module, but that's orthogonal to this issue.

 - **CC and CC:T impl:** These two would 'just' provide implementations for the CC API, mapping between CCEmuX's and CC's interfaces.

**Comment by dmarcuse** [comment]
In light of the upcoming [terminal rewrite in CC:T](https://github.com/SquidDev-CC/CC-Tweaked/pull/409), I think it'd make more sense to drop CC support from future versions of CCEmuX and rewrite it around CC:T exclusively. I don't think there are many people still using vanilla CC at this point, and those that are can still use old versions of CCEmuX (we could provide a legacy build for vanilla CC on the website). Any major new features could be backported if necessary.

This would avoid a lot of duplication of effort, and depending on how the terminal rewrite is implemented, we could theoretically use it directly for rendering to get perfectly emulated rendering. Other benefits include ditching the fragmentation of the AWT/JFX renderers to provide a single OpenGL renderer, keycodes that exactly match the in-game ones, and minimizing the CC:T rendering API surface so that further changes can be made without breaking compatibility.

**Comment by SquidDev** [comment]
Yeah, I have also considered that. I dunno, there's a bit of me which likes having both, though I realise I haven't even tested the CC version for a year now.

As far as renderers go, I guess it'd make sense to jump to 1.14/1.15 CC:T? That'd mean we can just use LWJGL 3, where the key codes are identical.

**Comment by dmarcuse** [comment]
That's what I was thinking. I vaguely recall some issues with multi-window support when we originally tried using LWJGL 3 for CCEmuX, but I don't remember the specifics. Once the terminal rewrite is functional, I can start experimenting with it to see how feasible it would be to use it directly.

**Comment by exerro** [comment]
If it's at all relevant, I've used LWJGL 3 with multiple windows plenty and it works fine. There were a few hiccups that were caused by not having the gl context current when swapping buffers iirc.

**Comment by SquidDev** [comment]
Given that Minecraft 1.16 is releasing next week, I'm probably going to be dropping support for 1.12.2. This pretty much forces us to drop CC support or implement a compatibility layer, as there's no longer any compatibility between the two.

One thing I'm a little worried about is how the launcher will handle the lack of CC updates. I don't know if it's worth just re-uploading the older versions for each new release as a stop-gap until we update the launcher.

**Comment by SquidDev** [comment]
#140 has updated to the 1.15 version of CC:T and dropped support for CC, so this issue is kinda dead now. CC will continue to be supported by the way of a nginx rule:

```nginx
location ~* ^/versions/([a-f0-9]+)/CCEmuX-cc\.jar$ {
  try_files $uri /versions/b9c413d9/CCEmuX-cc.jar =404;
}
```
