### ISSUE TITLE
[Question] Changing CC:T jar file?

### ISSUE THREAD

**Issue by znepb** [CCEmuX/CCEmuX#137]
Is there a way to change what jar file is being used by CC:T? I want to use it to test new features on CC:T that haven't been pushed yet.

**Comment by Lemmmy** [comment]
I'm not sure if you saw my message earlier, but mouse_move needs to be explicitly supported by the emulator and simply changing the jar won't work

**Comment by znepb** [comment]
Ah, okay. Guess I didn't see that.

**Comment by Lemmmy** [comment]
Yeah you seem to be good at only reading 1 in 5 of my messages

**Comment by znepb** [comment]
It seems so.

**Comment by SquidDev** [comment]
We have discussed building CCEmux on every CC:T commit, like I do for copy-cat, but it is a bit of a faff.

**Comment by znepb** [comment]
Okay, I decided to try and implement mouse_move on my own. It worked with JFX and AWT. But, currently it does not have throttling. I'll look into @Lemmmy's code to try and figure this out. I'll submit a new issue & a PR for this.
