### ISSUE TITLE
[SUGGESTION] Sound to attach if it is CC:T

### ISSUE THREAD

**Issue by QuickMuffin8782** [CCEmuX/CCEmuX#142]
I'd love to see the addition to playing sounds in the CC:T option for CCEmuX!
If that happens, I'll be able to listen to every single minecraft sound! (You can get all the sounds from the default pack, even update when a new version of minecraft reguarding any sound addition happens)

Reguards,
   QuickMuffin8782

**Comment by QuickMuffin8782** [comment]
(github must of doubled this!) closed now

**Comment by QuickMuffin8782** [comment]
I saw double on my screen. Sorry.

**Comment by SquidDev** [comment]
Duplicate of #143.
