### ISSUE TITLE
`fs.open` leaks the path to CCEmuX's data directory from within CraftOS through error message

### ISSUE THREAD

**Issue by MCJack123** [CCEmuX/CCEmuX#144]
If a program attempts to write to a file path that's too long, the error message will contain not only the internal path to the file that was attempted to be written to, but the entire absolute path to the file. This could let malicious programs leak personal information like the user's username or operating system.

To reproduce, call `fs.open(("\195\166"):rep(256), "w")` in the Lua shell. I expect the error message (second value) to be something like "/A|A|...: File name too long", but instead it also contains the absolute path to the file (in my case, "/Users/jack/Library/Application Support/ccemux/computer/0/A|A|...: File name too long").

**Comment by SquidDev** [comment]
I'm unable to reproduce on Windows (even with higher path lengths, such as 2<sup>20</sup>), so I wonder if this is a OSX problem?

I suspect this is a CC(: Tweaked) problem - CCEmuX just uses CC's own mount classes. Would you be able to try to reproduce in Minecraft itself?

**Comment by MCJack123** [comment]
I initially tested this in Minecraft on Windows, and did not get an error, so I thought it was a CCEmuX bug. However, after testing it in Minecraft on Mac, I got the same error. I have also found a different method of getting an error for Windows. I'll be closing this issue and moving it to [SquidDev-CC/CC-Tweaked](https://github.com/SquidDev-CC/CC-Tweaked).
