### ISSUE TITLE
[id] addition to 'emu open' command

### ISSUE THREAD

**Issue by SeaRuxTheHuman** [CCEmuX/CCEmuX#146]
Currently the command `emu data` only opens the emu's root folder, I believe
the addition of an id argument to this command would be a very useful time-save.

An example of what I mean would be something like: `emu data [id]`
that could open the folder for the computer with the id of **[id]**.
If an id argument is not given it could just open the root folder like normal

Yes, I understand it takes like 2 seconds to navigate to this folder manually, but I think it would be a nice time save :)

**Comment by SquidDev** [comment]
I assume you're referring to the `emu data` command, rather than `emu open`? The latter opens the emulator, rather than a directory!

**Comment by JakobDev** [comment]
Ithink he means emu open. e.g. emu open 1 would open a computer with computer/1 as it's root directory.

**Comment by SquidDev** [comment]
`emu open 1` does that already, and `emu open` opens a new computer rather than the "root folder" as mentioned in the OP.

**Comment by SeaRuxTheHuman** [comment]
sorry i meant `emu data`, will fix now
