### ISSUE TITLE
Numpad enter treated as normal enter key

### ISSUE THREAD

**Issue by MCJack123** [CCEmuX/CCEmuX#150]
When pressing the numpad enter key, it's reported as a standard enter key:

![image](https://user-images.githubusercontent.com/6236912/103845047-41c2b680-5069-11eb-82e2-41a4937a50c2.png)

I'd expect it to show `key 335 false` instead of `key 257 false`. To reproduce, press the numpad enter key on a full-size keyboard while pulling a `key` event.

**Comment by SquidDev** [comment]
Ahh, woops. Guess I missed this in the update to post-1.13 versions of CC.
