### ISSUE TITLE
Plugin creation guide request... Unable to create plugin.

### ISSUE THREAD

**Issue by MAGGen-hub** [CCEmuX/CCEmuX#165]
I need help...
I wanted tocreate a simple plugin that will allow user open emu iterations with different terminal sizes.
Unfortunatly I bumped into problems:

1. No guide.
I found absolutly no information about plugin creation for CCEmuX.
Thanks to CC:T Discord I got link to this: https://github.com/Lustyn/MinimalPeripheralsCCEmuX
So after that I realised that plugin required `resources/META-INF/services/`

2. No posible way to create custom (not builtin) plugin.
Well. I tried to use `build` `jar` and other gradle comands to create plugin but after I tried to turn it into jar I always got that:
![image](https://github.com/CCEmuX/CCEmuX/assets/56871670/c73864ee-0015-4c92-ab40-8e2d4d05a72a)

Please help me to solve that problem... What dependency my module need to have to avoid that?
```[ComputerCraft-Computer-Worker-0] ERROR dan200.computercraft.core.lua.BasicFunction -  COMPUTER_ERROR.JAVA Error calling openEmuWithSize on net.maggen.ccemux.CCEmuXAPIOpenWithSizePlugin$API@7c00af56
java.lang.NoClassDefFoundError: net/maggen/ccemux/CCEmuXAPIOpenWithSizePlugin$API
	at net.maggen.ccemux.CCEmuXAPIOpenWithSizePlugin$API$cc$openEmuWithSize80.apply(CC generated method)
	at dan200.computercraft.core.lua.BasicFunction.invoke(BasicFunction.java:45)
	at org.squiddev.cobalt.OperationHelper.invoke(OperationHelper.java:450)
	at org.squiddev.cobalt.function.LuaInterpreter.nativeCall(LuaInterpreter.java:612)
	at org.squiddev.cobalt.function.LuaInterpreter.execute(LuaInterpreter.java:408)
	at org.squiddev.cobalt.function.LuaInterpretedFunction.invoke(LuaInterpretedFunction.java:143)
	at org.squiddev.cobalt.LuaThread.loop(LuaThread.java:341)
	at org.squiddev.cobalt.LuaThread.run(LuaThread.java:322)
	at org.squiddev.cobalt.LuaThread.run(LuaThread.java:318)
	at dan200.computercraft.core.lua.CobaltLuaMachine.handleEvent(CobaltLuaMachine.java:130)
	at dan200.computercraft.core.computer.ComputerExecutor.resumeMachine(ComputerExecutor.java:601)
	at dan200.computercraft.core.computer.ComputerExecutor.work(ComputerExecutor.java:567)
	at dan200.computercraft.core.computer.ComputerThread$Worker.runImpl(ComputerThread.java:617)
	at dan200.computercraft.core.computer.ComputerThread$Worker.run(ComputerThread.java:567)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: net.maggen.ccemux.CCEmuXAPIOpenWithSizePlugin$API
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more
```

My code:
```package net.maggen.ccemux;

import com.google.common.io.ByteStreams;
import dan200.computercraft.api.lua.ILuaAPI;
import dan200.computercraft.api.lua.LuaFunction;
import net.clgd.ccemux.api.emulation.Emulator;
import net.clgd.ccemux.api.emulation.filesystem.VirtualFile;
import net.clgd.ccemux.api.plugins.Plugin;
import net.clgd.ccemux.api.plugins.PluginManager;
import net.clgd.ccemux.api.plugins.hooks.ComputerCreated;
import net.clgd.ccemux.api.plugins.hooks.CreatingROM;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import java.io.IOException;
import java.util.Collection;
import java.util.Collections;
import java.util.Optional;


public class CCEmuXAPIOpenWithSizePlugin extends Plugin {
	private static final Logger log = LoggerFactory.getLogger(CCEmuXAPIOpenWithSizePlugin.class);

	public static class API implements ILuaAPI {
		private final Emulator emu;

		public API(Emulator emu) {
			this.emu = emu;
		}

		@LuaFunction
		public final int openEmuWithSize(Optional<Integer> id,Optional<Integer> width,Optional<Integer> heigth) {
			//log.info("Open With Size info {} {} {}",id,width,heigth);
			return emu.createComputer(b -> b.id(id.orElse(-1)).termSize(width.orElse(emu.getConfig().termWidth.get()),heigth.orElse(emu.getConfig().termHeight.get()))).getID();
		}



		@Override
		public String[] getNames() {
			return new String[] {"ccemux_open_with_size_temp"};
		}
	}

	@Nonnull
	@Override
	public String getName() {
		return "CCEmuX API Open with Size Addition";
	}

	@Nonnull
	@Override
	public String getDescription() {
		return "Adds openEmuWithSize to 'ccemux' Lua API. That method allows user open new CCEmuX iterations with different sizes.";
	}

	@Nonnull
	@Override
	public Optional<String> getVersion() {
		return Optional.empty();
	}

	@Nonnull
	@Override
	public Collection<String> getAuthors() {
		return Collections.emptyList();
	}

	@Nonnull
	@Override
	public Optional<String> getWebsite() {
		return Optional.empty();
	}

	@Override
	public void setup(@Nonnull PluginManager manager) {
		registerHook((ComputerCreated) (emu, computer) -> computer.addApi(new API(emu)));
		registerHook((CreatingROM) (emu, romBuilder) -> {
		try {
			romBuilder.addEntry("programs/emu.lua", new VirtualFile(
				ByteStreams.toByteArray(CCEmuXAPIOpenWithSizePlugin.class.getResourceAsStream("/rom/emu_program_open_with_size.lua"))));
			romBuilder.addEntry("autorun/emu_add1.lua", new VirtualFile(
				ByteStreams.toByteArray(CCEmuXAPIOpenWithSizePlugin.class.getResourceAsStream("/rom/emu_autorun_open_with_size.lua"))));
		} catch (IOException e) {
			log.error("Failed to register ROM entries", e);
		}
		});
	}
}```

**Comment by SquidDev** [comment]
Yeah, the plugin API has always been a bit of a neglected feature there. Will try to look at fleshing out the Javadoc, even if nothing else.

That second issue appears to be a problem with how CC:T generates classes for `@LuaFunction` methods - they're injected into the main classloader, which doesn't have access to the plugin classes, and so it all fails at runtime.

This probably needs fixing on the CC:T end, but a workaround for now would be to use `IDynamicLuaObject` instead of `@LuaFunction`, skipping all the class generation shenanigans.

**Comment by MAGGen-hub** [comment]
> Yeah, the plugin API has always been a bit of a neglected feature there. Will try to look at fleshing out the Javadoc, even if nothing else.
> 
> That second issue appears to be a problem with how CC:T generates classes for `@LuaFunction` methods - they're injected into the main classloader, which doesn't have access to the plugin classes, and so it all fails at runtime.
> 
> This probably needs fixing on the CC:T end, but a workaround for now would be to use `IDynamicLuaObject` instead of `@LuaFunction`, skipping all the class generation shenanigans.

Thank you  for your answer. So now it's imposible to create custom plugin? 
Then can I ask you for an improvement/enhancement for CCEmuX?
I really need `emu.open` be able to open terminals with diffenet sizes... Because it's comfortable to program in big sized terminal, but test in default (19/55) sized ingame terminal.
It also could be very nice to make `emu.open` be able to execute commands and change the terminal scale after shell loaded, but well I think that can be created after plugin-API fix...

Actualy is it posible to "fix" that problem now somehow? I mean what I need in dependencies to make my plugin work?The whole `dan200.computercraft.api`? Or mabe adding something into manifest calss-path variable could make a deal? Or it's currently imposible to fix???  I searched for `IDynamicLuaObject` but not found it (can you tell me where is it located?)...

**Comment by SquidDev** [comment]
> So now it's imposible to create custom plugin?

No, it should be possible. It's just can't create a plugin which adds a new `ILuaAPI` with `@LuaFunction`. It's nothing wrong with your dependencies, just a conflict between CC:T and how CCEmuX's plugin loader works.

> I searched for `IDynamicLuaObject` but not found it (can you tell me where is it located?)...

It lives at [`dan200.computercraft.api.lua.DynamicLuaObject`](https://tweaked.cc/mc-1.19.x/javadoc/dan200/computercraft/api/lua/IDynamicLuaObject.html).


> Then can I ask you for an improvement/enhancement for CCEmuX? I really need `emu.open` be able to open terminals with different sizes.

Yeah, that seems a sensible feature to add.

**Comment by MAGGen-hub** [comment]
> > So now it's imposible to create custom plugin?
> 
> No, it should be possible. It's just can't create a plugin which adds a new `ILuaAPI` with `@LuaFunction`. It's nothing wrong with your dependencies, just a conflict between CC:T and how CCEmuX's plugin loader works.
> 
> > I searched for `IDynamicLuaObject` but not found it (can you tell me where is it located?)...
> 
> It lives at [`dan200.computercraft.api.lua.DynamicLuaObject`](https://tweaked.cc/mc-1.19.x/javadoc/dan200/computercraft/api/lua/IDynamicLuaObject.html).

Thank you very much. I still don't fully understand how to work with `IDynamicLuaObject` but guess it's as simple as with `@LuaFunction`.

**Comment by MAGGen-hub** [comment]
Excuse me... I don't undrestand how can I enable method using `IDynamicLuaObject`... I created a class for `openEmuWithSize` that implements `IDynamicLuaObject` but after that I got stuck... What I need to do with it? How can I turn it into Lua function? I need to create a perepherial object with `IDynamicLuaObject` and after that load it as peripherial? Or there is a function exist that will push `openEmuWithSize` to _G table?
Sorry...

**Comment by MAGGen-hub** [comment]
Sorry again... Guess I found the solution `	public static class API implements ILuaAPI,IDynamicLuaObject`

**Comment by MAGGen-hub** [comment]
THANK YOU VERY MUCH AGAIN I MADE IT WORK IT'S WORKING!!!
Now I need to find the way to add command-auto-launch and and other things to create full testing/developing environment! (I don't think I need java functions for it, simple addition to shell startup could make a deal)
![image](https://github.com/CCEmuX/CCEmuX/assets/56871670/8953add6-fc8b-46b7-be1a-c4db9236cf65)

**Comment by SquidDev** [comment]
Awesome!

While I've got you here, can I get you to comment on https://github.com/cc-tweaked/CC-Tweaked/issues/1339#issuecomment-1488255817? I'm currently trying to relicense bits of CC:Tweaked, and you made some contributions a couple of years back (https://github.com/cc-tweaked/CC-Tweaked/pull/918).

**Comment by MAGGen-hub** [comment]
What I need to comment? Just say that `I am here` or copy the issue I described here?

**Comment by MAGGen-hub** [comment]
Found it. Commenting. `I permit the license of my contributions to the CC: Tweaked project to be changed to the Mozilla Public License, v. 2.0.`

**Comment by MAGGen-hub** [comment]
Oh! Can I have a question about Mozilla Public License, v. 2.0. I am not very doog at licences so... Is it more free than the licence that ComputerCraft have now?

**Comment by SquidDev** [comment]
Yes. The original post in #1339 goes into this in a bit more detail, as well as motivation and why the alternatives are less good, but the TLDR is that the current license CC uses a) requires any projects using CC's code to be licenced under the same licenced and b) prohibits using any of its code outside of Minecraft.

The MPL 2.0 is a much more "normal" license. It's a weak copyleft license, which means that projects using CC's code must make their changes available, but otherwise can do what they want.

**Comment by MAGGen-hub** [comment]
> prohibits using any of its code outside of Minecraft.

Holy mama! I hate that rule so much! That part of CCPL is really annoing... 
If after changing licence to MPL2.0 default `/rom` package will usable out of Minecraft I will mark the "licence changing day" as one of the best days in my life! 

Aclualy, my "contributions" are not very important for CC:T project.
I just added a few (1-3) strings that made usage of pocet computers a bit more comfortable, so...
Feel free to use that code under any licence in any situations, I don't really cares about it)))

**Comment by SquidDev** [comment]
> That second issue appears to be a problem with how CC:T generates classes for `@LuaFunction` methods - they're injected into the main classloader, which doesn't have access to the plugin classes, and so it all fails at runtime.

cc-tweaked/CC-Tweaked#1579 should resolve this, though have not tested on the CCEmuX end.
