### ISSUE TITLE
I can't attach a monitor 

### ISSUE THREAD

**Issue by Hardrex** [CCEmuX/CCEmuX#166]
hello, I remember almost a year ago that I used the emulator, at that time I could emulate monitors to be able to use them with the emulated computer.

the thing is that recently, I wanted to use the emulated computer again and I find that it is no longer possible to create monitors, I try to use "ccemux.attach("left", "monitor")".

and this does not work, the emulator mentions that there is no such peripheral, I do not know what is happening, thank you for your attention and I hope for an answer. 

![image](https://github.com/CCEmuX/CCEmuX/assets/83193585/7f9fac16-ad23-4de6-bff1-d5797e183dd1)

**Comment by SquidDev** [comment]
Did you possibly use [CraftOS-PC](https://www.craftos-pc.cc/) before? I believe they have a monitor peripheral.
