### ISSUE TITLE
CCEmuX won't launch

### ISSUE THREAD

**Issue by PixelatedPerfection** [CCEmuX/CCEmuX#168]
exactly as it says in the title
no matter how many times i click on the launcher, nothing happens.
it gave me the prompt the first time, and after i selected it, it closed, and now no longer works
I've tried redownloading it serveral times, and tried reopening it several times, but nothing works
no matter how many times i try, it doesn't open anything
there's no errors, no anything, it just wont open

**Comment by SquidDev** [comment]
Oh, that's very odd! Would you be able to run the launcher from the command line (`java -jar ccemux-launcher.jar`), and paste the output here?

**Comment by SquidDev** [comment]
Oh, make sure you're running a recent version of Java. It's possible you've only got Java 8 - you'll need at least Java 17.

**Comment by PixelatedPerfection** [comment]
oh okay, ill try that first one, then ill see about updating java, ill be back momentarily

edit: trying to run the jar through CMD with the command you sent gave the following response:
`Error: Unable to access jarfile ccemux-launcher.jar`

edit 2: I currently have Javas 7, 8, and SE Development Kit 17.0.8 installed (I forget why I have multiple installed but I think I was encountering problems with something in the past that made me install multiple)
is SE Development Kit not what it wants, or should I look for an even more recent version of Java?

**Comment by SquidDev** [comment]
Ahh sorry, had missed your edits here!

> edit: trying to run the jar through CMD with the command you sent gave the following response:
`Error: Unable to access jarfile ccemux-launcher.jar`

Oh sorry, `ccemux-launcher.jar` should be replaced with the path to the actual launcher. So if it's not called `ccemux-launcher.jar` (or is in a different directory), you'll need to put the whole path there.

If you've got multiple versions of Java installed, is possible its defaulting to a different version. Running `java -version` should print out which version you have.

**Comment by PixelatedPerfection** [comment]
> Ahh sorry, had missed your edits here!
Tis fine, dw
> you'll need to put the whole path there.
ah, didn't realize that (im not the most tech literate sometimes lmao)
> Running `java -version` should print out which version you have.
did that, the version it focused on was the SE 17.0.8 version

anyways, im sorry if this is also a result of me not being too tech smart but i put in the full path like this
`C:\Users\(my computer name)\Desktop\mc mods\computercraft\ccemux-launcher.jar` and it said
`Error: Unable to access jarfile C:\\Users\\(my computer name)\\Desktop\\mc` (yes it cut off like that)

**Comment by SquidDev** [comment]
Ahh, sorry! If you've got spaces in the name, you'll need to wrap the whole thing in quotes (so `java -jar "C:\Users\(my computer name)\Desktop\mc mods\computercraft\ccemux-launcher.jar"`).

**Comment by PixelatedPerfection** [comment]
OHHHH okay, thank you!

**Comment by PixelatedPerfection** [comment]
IT WORKED!
Thank you!

**Comment by SquidDev** [comment]
Yay!

The fact that it doesn't work if you click, but does if you run from the command line, suggests the file association might be pointing to an older Java version. You might have some luck [running the Jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) program - I'm afraid I don't use Windows, so don't have much experience with this.
