### ISSUE TITLE
Better documentation of emu command

### ISSUE THREAD

**Issue by Lemmmy** [CCEmuX/CCEmuX#20]
Document the actual list of arguments and possible settings values instead of a list of examples (for example the `resolution` setting can also be set to `pocket` or `computer` but this is undocumented)

**Comment by Lignumm** [comment]
We should also add autocompletion to the command somehow. That would require editing `startup`, so that might not be as easy as it sounds.

**Comment by SquidDev** [comment]
I *think* everything in the `rom/autorun` direction is executed: you could add your auto-completion script there.

**Comment by Lignumm** [comment]
Oh, right. That should be simple enough then, considering that we're already hacking the `emu` program into the rom.

**Comment by apemanzilla** [comment]
Speaking of which we should find a better way to load stuff into the rom, right now you have to make a `ComboMount` containing a mount for every single file which can't be good for performance or usability. Maybe write a gradle task that compresses `src/main/custom-rom` insto `src/resources/rom.zip` or something?

**Comment by SquidDev** [comment]
@apemanzilla Can you not use a `JarMount` on the CCEmuX file instead?

**Comment by Lignumm** [comment]
@apemanzilla And anyway, you're always loading the program for any `createResourceMount` call, no matter the arguments, which can't be correct. Perhaps we should do something more like what [we used to do](https://github.com/Lignumm/CCEmuX/blob/master/src/main/java/net/ceriat/clgd/ccemux/emulation/ROMPatcher.java#L13).

**Comment by Lemmmy** [comment]
:hankey: :us:

**Comment by apemanzilla** [comment]
Working on a better custom rom system now

**Comment by SquidDev** [comment]
Just wondering what needs doing to this? `emu set` isn't a thing any more so we don't need to document any of the settings.

It might be worth creating a documentation file for the `ccemux` API, but that's a whole different issue :).

**Comment by dmarcuse** [comment]
Adding documentation for the `ccemux` API is a good idea, but I wonder if (using the new custom ROM system) it could be automatically generated?

**Comment by Lemmmy** [comment]
vigus dickus
