### ISSUE TITLE
Disk/basic peripheral support

### ISSUE THREAD

**Issue by apemanzilla** [CCEmuX/CCEmuX#26]
I feel like this is one thing that no existing emulator does well, making it difficult for the users. I would like to implement this in a way that you can just run `ccemux.setPeripheral("top", "drive", id)` or `ccemux.setPeripheral("top", "wireless_modem", x, y, z)`. It should also be integrated with the `emu` program for ease of use.

**Comment by Lignumm** [comment]
How are we going to map the peripheral names to their classes? `IPeripheral` has getName (or whatever it is), but I'm not sure if iterating over every `IPeripheral` and putting it in a map is a great idea. Or is there some method I'm unaware of?

**Comment by SquidDev** [comment]
You'll have to recreate any peripherals you want. Almost all CC peripherals depend on Minecraft code (extend the `TileEntity` class, use `World`) which isn't on your class path and so will crash if you try to use them.

**Comment by Lemmmy** [comment]
you could create basic wrappers with minimal behaviour in a package with the same names as minecraft classes

**Comment by apemanzilla** [comment]
OK, so:
- Rednet - possible
- Note blocks - not really possible (needs Minecraft sounds, would be a hassle)
- Disk drives - possible
- Printers - possible but no one uses those anyways and you wouldn't be able to view printed pages unless someone wrote a custom renderer....

If you guys have other ideas let me know.

**Comment by hugeblank** [comment]
Maybe you guys could do monitors too? you already have computers in place, and I'm pretty sure you can vary the amount of pixels too, so it wouldn't be far from what you already have.

Another one that's possible is wired modems, seeing as you already have plans for wireless modems. Along with the five other sides that are open, you could have a "network" 'side' to attach peripherals to. However this is a bigger issue when you add more than one wired modem to a single computer, so maybe it's a bit more of a hassle than it's worth.

**Comment by SquidDev** [comment]
I've added basic support for disk drives and wireless modems. Is there anything else which can be trivially added?

 - Speakers are _technically_ possible but would require substantial effort to load MC's assets. Same goes for records in disk drives.
 - Monitors would require a bit of a rework of the rendering API.
 - Wired modems and printers seem a little overkill: I'd suggest people just use MC if they need this.

**Comment by dmarcuse** [comment]
Maybe other computers? Although the implementation would be a bit hacky I think.

**Comment by Lustyn** [comment]
[Speakers have been done in the past](https://github.com/justync7/MinimalPeripheralsCCEmuX), but its super difficult without setting up something like OpenAL to get pitching identical to that of minecraft.

Wrapping other computers should be fairly easy, you can just implement something like

     ccemux.attach("left","computer",{id=1})

and then you can access the computer with ID 1 on the left.

**Comment by dmarcuse** [comment]
The problem is that to properly emulate CC behavior, it shouldn't wrap all computers with the ID as a peripheral, just the "adjacent" one. This means we'd need to create and add a new computer whenever you attach one as a peripheral, or add a way to select an existing one.

**Comment by Lemmmy** [comment]
with regard to note blocks, I have experience with DSP from jmodular and jperformer - I could probably get proper note block pitching working using only java sound

**Comment by dmarcuse** [comment]
@Lemmmy if you're willing to, I think it would be a really good feature that sets CCEmuX apart from other emulators
