### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by Lemmmy** [CCEmuX/CCEmuX#36]
A key-value based storage per-computer that is persistent

`ccemux.putStorage(key, value)`
`ccemux.getStorage(key, default?)`
`ccemux.hasStorage(key)`
`ccemux.listKeys()`

**Comment by apemanzilla** [comment]
Alternatively it could be implemented as a separate API with it's own config option:
```lua
storage.put(key, value)
storage.get(key)
storage.hasKey(key)
storage.keys()
```

**Comment by Lemmmy** [comment]
I'm not sure - `storage` could conflict with a user-defined API. However, this is certainly cleaner.

**Comment by apemanzilla** [comment]
Maybe `ccemux.storage().get(key)`, etc

**Comment by apemanzilla** [comment]
Is there any real use case for this? I think it would be better implemented as an optional plugin or something.

**Comment by dmarcuse** [comment]
Closing this for now, I don't really see any use cases that wouldn't be satisfied by files and/or the settings API
