### ISSUE TITLE
Use the native paste event

### ISSUE THREAD

**Issue by Lignum** [CCEmuX/CCEmuX#38]
We're currently checking for Ctrl+V presses, however, some environments have other methods of pasting, such as pressing middle click.

~There's probably an event we can listen to.~ Apparently, `KeyEvent.VK_PASTE` will be fired on any type of paste.

**Comment by SquidDev** [comment]
Whilst this does seem a sensible idea, it does mean that the emulator won't perfectly reflect CC's behaviour. There doesn't seem to be a way to capture "native" paste events in CC, so there's little hope of it changing on that end. All in all, I think it's best to stick to the current behaviour.

**Comment by dmarcuse** [comment]
We could add a config option. On Linux especially being able to use the different clipboards is handy.
