### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by apemanzilla** [CCEmuX/CCEmuX#53]
The documentation right now is pretty lacking, if we want people to start writing plugins for it we should make it easier to understand.

**Comment by apemanzilla** [comment]
The readme is also outdated, have to fix that after merging plugins.

**Comment by MineRobber9000** [comment]
Quick plugin question: how do I register a hook? do I make an instance of the class made that implements the hook and pass it or do I just pass the implementing class?

**Comment by dmarcuse** [comment]
First off make sure your plugin class extends [Plugin](https://github.com/Lignum/CCEmuX/blob/master/src/main/java/net/clgd/ccemux/plugins/Plugin.java). From there, you should implement `Plugin.setup`, which will be called when your plugin is loaded. You can use `Plugin.registerHook` to register one or more [hooks](https://github.com/Lignum/CCEmuX/tree/master/src/main/java/net/clgd/ccemux/plugins/hooks) at this point.

Additionally, you need to add a service file that lists your plugin class, and include this file when distributing your plugin. This file should be placed in `META-INF/services`, named `net.clgd.ccemux.plugins.Plugin`, and contain one plugin class per line, with no `.java` or `.class` extension. ([Example](https://github.com/Lignum/CCEmuX/blob/master/src/main/resources/META-INF/services/net.clgd.ccemux.plugins.Plugin))

If you want some examples, there are [two built-in plugins](https://github.com/Lignum/CCEmuX/tree/master/src/main/java/net/clgd/ccemux/plugins/builtin) that you can look through, although neither makes use of hooks.

**Comment by MineRobber9000** [comment]
Which hook, and what method, should I use to add an ILuaAPI to an `EmulatedComputer`? Is it a method on the computer itself, or is it a call to the CCEmuX object?

**Comment by dmarcuse** [comment]
You should use the [ComputerCreated](https://github.com/Lignum/CCEmuX/blob/1.8/src/main/java/net/clgd/ccemux/plugins/hooks/ComputerCreated.java) hook, and register the API with a `Computer.addAPI` call. Use the [`CCEmuXAPI` plugin](https://github.com/Lignum/CCEmuX/blob/1.8/src/main/java/net/clgd/ccemux/plugins/builtin/CCEmuXAPI.java) as an example. (Also a good example of custom ROM entries)

**Comment by dmarcuse** [comment]
Plugin API documentation is decent now
