### ISSUE TITLE
Debug API

### ISSUE THREAD

**Issue by A-Cloud-Ninja** [CCEmuX/CCEmuX#67]
I note that CCEmuX has CCTweaks in it, but does not seem to have the debug api? Is there a reason behind this?

**Comment by dmarcuse** [comment]
You probably just need to enable the debug API in CCTweaks.

**Comment by dmarcuse** [comment]
I've tested it and it works properly for me - follow these instructions to enable it:

1. Open CCEmuX and run `emu data` in the emulator
2. Open the `plugins` folder in the window that opens
3. Open (or create and open) the `config` folder in the plugin folder
4. Make a new file, named *exactly* `net.clgd.ccemux.plugins.builtin.CCTweaksPlugin.json`
5. Enter this and save the file: `{"APIs.debug":"true"}`
6. Restart CCEmuX
