### ISSUE TITLE
[Probably known] Unable to build emulator

### ISSUE THREAD

**Issue by hugeblank** [CCEmuX/CCEmuX#92]
[build.txt](https://github.com/CCEmuX/CCEmuX/files/1832362/build.txt)
For some reason beyond me I can't seem to get the emulator to build and compile. I left the log when I try to build it above, if you could give me any pointers as to what I may be doing wrong, I could really use the assistance. I'm 90% sure this is either something I'm doing wrong, or something you're already aware of, but I figured there's no harm in posting this as an issue.

**Comment by SquidDev** [comment]
For some reason JFX isn't part of your JDK install. I'm not even sure how this is possible - what version/JDK are you using?

**Comment by dmarcuse** [comment]
OpenJDK doesn't include JavaFX, and IIRC neither does Oracle JDK 10+. Install the appropriate version and building should work fine.

**Comment by hugeblank** [comment]
hum okay, thanks for the help. @apemanzilla any idea where I could find the appropriate version of java?

**Comment by SquidDev** [comment]
[Here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Comment by hugeblank** [comment]
thank you! @SquidDev

**Comment by hugeblank** [comment]
will java 10 in the future include JFX? It's obviously something necessary for this emulator, or maybe you guys will be moving the emulator out from using JFX?

**Comment by Lemmmy** [comment]
theres many differnt builds of java, some include jfx, some don't - it's not a matter of the java version, but instead a matter of which java impl you're using
