### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by dmarcuse** [CCEmuX/CCEmuX#99]
As discussed in Slack, a launcher (**as a separate project**) would help streamline updating CCEmuX, as well as managing different versions. Here's what I think would work best to maintain a smooth user experience.

1. Launcher is started by user (separate jar from rest of CCEmuX)
2. If no version is currently downloaded, show a status dialog or splash while downloading the latest version
3. Launch the latest version of CCEmuX in a new thread (construct new classloader with CCEmuX and dependencies, load and invoke main class, pass arguments as appropriate)
4. Start a new daemon thread
    1.  Check if a new version is available (limited to once per hour/day/etc?)
    2. Download new version if available, to be used for next launch (check for compatibility before downloading, notify user if incompatible?)
    3. Send user a desktop notification that a new version will be used next launch, with an option to immediately restart or show changelog
    4. Delete old versions?
5. If CCEmuX crashes, catch error and display a friendly crash report with an option to open an issue

**Benefits of this approach**

- Maintains the streamlined user experience, doesn't add unnecessary startup time
- Provides a smooth automatic update system, a la chrome
- Could improve crash detection and handling
- Opens up possibilities for other improvements
    - Download dependencies separately from main CCEmuX/CC jars to prevent duplicates
    - Allow users to select specific CCEmuX versions to use

**Potential issues to consider**

- How do we host and access version metadata - GitHub API and relases?
- How will the launcher itself be updated?
- **How will updating maintain compatibility with external plugins/resources** - do we finalize the plugin API to prevent issues when updating CCEmuX?
- How will arguments be handled - do we simply pass them all to CCEmuX?
- How will logging work? Do we separate logging for the launcher and CCEmuX?
- Running CCEmuX directly should still be possible (i.e. for development environments, or to use a specific version) - how does this limit what can be done through the launcher?

Let me know if anyone has suggestions, questions, or any other thoughts on this.

**Comment by SquidDev** [comment]
> Download dependencies separately from main CCEmuX/CC jars to prevent duplicates

For reference, CCEmuX takes up 180 kB on its own, about 8.5 MB without CC and 10 MB with it. We'd definitely save bandwidth if we only shipped the core (or even core + CC), but it does add complications to the whole launching process, keeping deps up-to-date, etc...

> Allow users to select specific CCEmuX versions to use

I'm not really sure I see the need of this - people can just download a specific version without using the launcher. That being said, it is worth bearing in mind what happens if there's a bug in an update - we should possibly give people the option to roll back.

> Running CCEmuX directly should still be possible. How does this limit what can be done through the launcher?

I think my biggest concern would be crash reporting. Do we have two crash handlers - one in the launcher and one in the main app? I think the best thing to do here would be to get the launcher doing as little as possible - it just handles downloading, choosing and cleaning up versions. Obviously logging is a kerfuffle, but I don't think we need to add another crash handler.

**Comment by Lignum** [comment]
My personal biggest priority for this would be simplicity. The great thing about CCEmuX is that it's just windows with the emulator inside them, no clunky UI. In that spirit, I wouldn't like a big fancy Minecraft-style launcher that introduces another button to click before getting to the point.

**Comment by dmarcuse** [comment]
> I think my biggest concern would be crash reporting. Do we have two crash handlers - one in the launcher and one in the main app?

I was thinking of moving the crash reporting to the launcher entirely. Ideally, CCEmuX will only be run directly in things like development environments, where simply exiting and logging the exception is fine.

> We'd definitely save bandwidth if we only shipped the core (or even core + CC), but it does add complications to the whole launching process, keeping deps up-to-date, etc...

Yeah, it may be better to just download the complete jar. We can set up the launcher to delete old versions to avoid wasting disk space if necessary.

**Comment by dmarcuse** [comment]
> In that spirit, I wouldn't like a big fancy Minecraft-style launcher that introduces another button to click before getting to the point.

The only UI I was planning on implementing for the launcher would be a basic splash/status screen when run the first time to download CCEmuX, system tray notifications for when updates have been applied/failed, and a crash reporter.
